export const rootWebSocketURL = 'https://workable-oyster-regularly.ngrok-free.app/ws'
export const actions = {
  GENERATE_QUESTION: 'GENERATE_QUESTION',
  SELECT_REVIEWER: 'SELECT_REVIEWER',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  SHOW_RESULTS: 'SHOW_RESULTS',
  UPDATE_MODERATOR: 'UPDATE_MODERATOR',
  RETRIEVE_REVIEWER_LIST: 'RETRIEVE_REVIEWER_LIST',
  ERROR: 'ERROR',
}
export const questionType = {
  IDENTIFICATION: 'IDENTIFICATION',
  ENUMERATION: 'ENUMERATION',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
}