// 'https://workable-oyster-regularly.ngrok-free.app/ws'
export const rootWebSocketURL: string = 'http://127.0.0.1:8000/ws';

export const actions: Record<string, string> = {
  GENERATE_QUESTION: 'GENERATE_QUESTION',
  SELECT_REVIEWER: 'SELECT_REVIEWER',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  SHOW_RESULTS: 'SHOW_RESULTS',
  UPDATE_MODERATOR: 'UPDATE_MODERATOR',
  RETRIEVE_REVIEWER_LIST: 'RETRIEVE_REVIEWER_LIST',
  ERROR: 'ERROR',
  SUCCESS: 'SUCCESS',
  GET_ROOM_INFO: 'GET_ROOM_INFO',
  UPDATE_CONNECTED_USER: 'UPDATE_CONNECTED_USER',
  UPDATE_NUMBER_OF_SUBMISSIONS: 'UPDATE_NUMBER_OF_SUBMISSIONS',
};

export const questionType: Record<string, string> = {
  IDENTIFICATION: 'IDENTIFICATION',
  ENUMERATION: 'ENUMERATION',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
};